server:
  port: 9999

spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5
  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true


zuul:
  servlet-path: /api-gateway
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    own-file:
      path: /file/**
      serviceId: own-file
      stripPrefix: true
      sensitiveHeaders:
   own-product:
      path: /product/**
      serviceId: own-product
      stripPrefix: true
      sensitiveHeaders:
    own-promotion:
      path: /promotion/**
      serviceId: own-promotion
      stripPrefix: true
      sensitiveHeaders:
    own-send-server:
      path: /send/server/**
      serviceId: own-send-server
      stripPrefix: true
      sensitiveHeaders:
    own-user-party:
      path: /user/send/**
      serviceId: own-user-party
      stripPrefix: true
      sensitiveHeaders:
    own-workflow:
      path: /workflow/**
      serviceId: own-workflow
      stripPrefix: true
      sensitiveHeaders:



  ratelimit:
    key-prefix: proudkids-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true


security:
  validate:
    code: false
  sessions: stateless

urls:
  anon:
    - /swagger-resources/**
    - /swagger-ui.html
    - /swagger/api-docs

logging:
  config: classpath:logback.xml
